typography_spectrum: 0.8335591242648661
color:
  brandStrength: 0.054990642704069614
  lightness: 0.47215780010446906
  saturation: 0.9284956457559019
  rhythmicContrast: 0.6613505233544856
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
layout_spectrum: 0.0725388505961746
name: Im치genes de mis viajes
navigation:
  - name: Retratos callejeros
    id: 40c2cca2-d20b-4982-a111-a4381cbc2702
    type: content
title: Im치genes de mi viaje
description: >-
  Mi viaje por esta encarnaci칩n tiene cosas que vale la pena registrar, y quiero
  compartir la belleza que hay detr치s de una imagen
